# Generated by Django 5.0.2 on 2024-02-14 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('slug', models.CharField(max_length=40, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('price', models.IntegerField(null=True)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('active', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(upload_to='files/thumbnail/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('resource', models.FileField(upload_to='files/resource/')),
                ('time_to_complete', models.CharField(max_length=50, null=True)),
                ('numbers_of_chapter', models.IntegerField(null=True)),
                ('requirement_to_complete', models.CharField(max_length=100, null=True)),
                ('language', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('count', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=60, null=True)),
                ('pan_number', models.CharField(max_length=20, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tango.course')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='files/thumbnail/')),
                ('is_preview', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=40, null=True, unique=True)),
                ('serial_number', models.IntegerField(null=True)),
                ('complete_chapter', models.BooleanField(default=False)),
                ('number_of_videos', models.IntegerField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tango.course')),
            ],
        ),
        migrations.CreateModel(
            name='IpTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tango.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, null=True)),
                ('answer', models.CharField(max_length=150, null=True)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tango.chapter')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tango.course')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=150, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tango.chapter')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tango.questions')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_complete', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('complete_date', models.CharField(max_length=15, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tango.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField(null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tango.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usercourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tango.usercourse')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('profileid', models.CharField(max_length=30, null=True)),
                ('chapter', models.IntegerField(default=1)),
                ('institude', models.CharField(blank=True, max_length=60, null=True)),
                ('profession', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(null=True, upload_to='files/thumbnail/')),
                ('title', models.CharField(max_length=100, null=True)),
                ('serial_number', models.IntegerField(null=True)),
                ('video_id', models.FileField(null=True, upload_to='files/videos/')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tango.chapter')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tango.course')),
            ],
        ),
    ]
