# Generated by Django 5.0.2 on 2024-02-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0002_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
