# Generated by Django 5.0.2 on 2024-02-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0004_alter_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
