# Generated by Django 5.0.2 on 2024-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0005_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_up',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
