# Generated by Django 5.0.2 on 2024-02-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0008_alter_answers_answer_alter_questions_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=550, null=True),
        ),
    ]
