# Generated by Django 5.0.2 on 2024-02-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0009_alter_answers_answer_alter_questions_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='is_preview',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='complete_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
