# Generated by Django 5.0.2 on 2024-03-05 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0010_alter_chapter_is_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tango.payment'),
            preserve_default=False,
        ),
    ]
