# Generated by Django 5.0.2 on 2024-03-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0012_alter_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='payment',
        ),
    ]
