# Generated by Django 5.0.2 on 2024-03-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0013_remove_userprofile_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='csv_files/')),
            ],
        ),
    ]
