# Generated by Django 5.0.2 on 2024-03-06 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0014_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tango.course'),
            preserve_default=False,
        ),
    ]
