# Generated by Django 5.0.2 on 2024-03-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0015_csvfile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_Details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Intro_Video_ID',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
