# Generated by Django 5.0.2 on 2024-04-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0017_alter_course_intro_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
